/*
 *  Copyright 2009 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets.elf; 1, 0, 0,139; 12-18-2009 11:42:13; /db/ztree/library/trees/xdctargets/xdctargets-b30x/src/
 */

