/*
 *  Copyright 2009 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets; 1, 0, 3,372; 12-18-2009 11:42:09; /db/ztree/library/trees/xdctargets/xdctargets-b30x/src/
 */

