.bd B 3
.TH masm55 1 "Mar 02, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
masm55 - Mnemonic Assembler
.SH SYNOPSIS
.B masm55
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The mnemonic assembler accepts mnemonic assembly and converts it to algebraic assembly.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
