/*
 *  Copyright 2009 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets; 1, 0, 1,374; 12-18-2009 11:42:01; /db/ztree/library/trees/xdctargets/xdctargets-b30x/src/
 */

